/* eslint-disable no-console */
const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");
const crypto = require("crypto");

const ROOT = __dirname;
const DEPLOY_ROOT = path.join(ROOT, "upload_server_files");
const ONCE = process.argv.includes("--once");
const INTERVAL_MS = 1200;

const FRONTEND_ROOT = path.join(ROOT, "artifacts", "marketplace");
const BACKEND_ROOT = path.join(ROOT, "artifacts", "api-server");

const COPY_RULES = [
  {
    name: "frontend-build",
    src: path.join(FRONTEND_ROOT, "dist"),
    dest: path.join(DEPLOY_ROOT, "frontend", "dist"),
    optional: true,
  },
  {
    name: "frontend-package",
    src: path.join(FRONTEND_ROOT, "package.json"),
    dest: path.join(DEPLOY_ROOT, "frontend", "package.json"),
  },
  {
    name: "frontend-lock",
    src: path.join(ROOT, "pnpm-lock.yaml"),
    dest: path.join(DEPLOY_ROOT, "frontend", "pnpm-lock.yaml"),
    optional: true,
  },
  {
    name: "backend-package",
    src: path.join(BACKEND_ROOT, "package.json"),
    dest: path.join(DEPLOY_ROOT, "backend", "package.json"),
  },
  {
    name: "backend-lock",
    src: path.join(ROOT, "pnpm-lock.yaml"),
    dest: path.join(DEPLOY_ROOT, "backend", "pnpm-lock.yaml"),
    optional: true,
  },
  {
    name: "backend-tsconfig",
    src: path.join(BACKEND_ROOT, "tsconfig.json"),
    dest: path.join(DEPLOY_ROOT, "backend", "tsconfig.json"),
    optional: true,
  },
  {
    name: "backend-src",
    src: path.join(BACKEND_ROOT, "src"),
    dest: path.join(DEPLOY_ROOT, "backend", "src"),
  },
  {
    name: "database-seed",
    src: path.join(BACKEND_ROOT, "src", "lib", "seed.ts"),
    dest: path.join(DEPLOY_ROOT, "database", "seed.ts"),
    optional: true,
  },
  {
    name: "database-migrations",
    src: path.join(BACKEND_ROOT, "migrations"),
    dest: path.join(DEPLOY_ROOT, "database", "migrations"),
    optional: true,
  },
];

const EXCLUDED_NAMES = new Set(["node_modules", ".git", ".next", ".turbo", ".cache"]);

function isDotEnvFile(filePath) {
  const base = path.basename(filePath);
  return base === ".env" || base.startsWith(".env.");
}

async function exists(p) {
  try {
    await fsp.access(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(p) {
  await fsp.mkdir(p, { recursive: true });
}

async function removeIfExists(p) {
  if (await exists(p)) {
    await fsp.rm(p, { recursive: true, force: true });
  }
}

function sha1(content) {
  return crypto.createHash("sha1").update(content).digest("hex");
}

async function copyFileIfChanged(src, dest) {
  if (isDotEnvFile(src)) return;
  await ensureDir(path.dirname(dest));
  const srcBuf = await fsp.readFile(src);
  if (await exists(dest)) {
    const destBuf = await fsp.readFile(dest);
    if (sha1(srcBuf) === sha1(destBuf)) return;
  }
  await fsp.writeFile(dest, srcBuf);
}

async function syncDirectory(srcDir, destDir) {
  const srcExists = await exists(srcDir);
  if (!srcExists) return;

  await ensureDir(destDir);
  const srcEntries = await fsp.readdir(srcDir, { withFileTypes: true });
  const srcNames = new Set(srcEntries.map((e) => e.name));

  for (const entry of srcEntries) {
    if (EXCLUDED_NAMES.has(entry.name)) continue;
    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);

    if (entry.isDirectory()) {
      await syncDirectory(srcPath, destPath);
      continue;
    }
    if (entry.isFile()) {
      if (isDotEnvFile(srcPath)) continue;
      await copyFileIfChanged(srcPath, destPath);
    }
  }

  const destEntries = await fsp.readdir(destDir, { withFileTypes: true });
  for (const dEntry of destEntries) {
    const dPath = path.join(destDir, dEntry.name);
    if (!srcNames.has(dEntry.name)) {
      await removeIfExists(dPath);
    }
  }
}

async function syncRule(rule) {
  const srcExists = await exists(rule.src);
  if (!srcExists) {
    if (!rule.optional) {
      console.warn(`[warn] Missing required source: ${rule.src}`);
    }
    await removeIfExists(rule.dest);
    return;
  }
  const st = await fsp.stat(rule.src);
  if (st.isDirectory()) {
    await syncDirectory(rule.src, rule.dest);
  } else {
    await copyFileIfChanged(rule.src, rule.dest);
  }
}

function deployReadmeText() {
  return `# README_DEPLOY

This folder is auto-generated by \`sync-deploy.js\`.
Do not edit files here manually; edit source files in the main project.

## Folder Layout

- \`frontend/\`: production-ready frontend assets and runtime files.
- \`backend/\`: backend source, routes, models/controllers (inside \`src/\`), and server entry files.
- \`database/\`: seed/migrations snapshot for deployment.

## 1) Create ZIP Package

From project root:

\`\`\`bash
node sync-deploy.js --once
\`\`\`

Then compress \`upload_server_files/\` as:

\`\`\`
upload_server_files.zip
\`\`\`

## 2) Upload to Server

Upload the zip file to your VPS (example target: \`/var/www/dalil-plus\`), then:

\`\`\`bash
cd /var/www/dalil-plus
unzip -o upload_server_files.zip
\`\`\`

## 3) Install and Run (pnpm + pm2)

### Frontend
\`\`\`bash
cd /var/www/dalil-plus/upload_server_files/frontend
pnpm install --frozen-lockfile || pnpm install
# If you deploy prebuilt dist only, serve dist with Nginx or static host.
\`\`\`

### Backend
\`\`\`bash
cd /var/www/dalil-plus/upload_server_files/backend
pnpm install --frozen-lockfile || pnpm install

# Build if required by your backend setup
pnpm run build || true

# Start or restart via PM2
pm2 start "pnpm start" --name dalil-plus-api || pm2 restart dalil-plus-api
pm2 save
\`\`\`

## 4) Environment Variables

Use:
- \`frontend/.env.production.example\`
- \`backend/.env.production.example\`

Copy and fill real secrets on the server:

\`\`\`bash
cp backend/.env.production.example backend/.env
cp frontend/.env.production.example frontend/.env
\`\`\`

Never commit or upload real \`.env\` values.

## 5) Continuous Sync (Local)

To keep deployment folder always updated while developing:

\`\`\`bash
node sync-deploy.js
\`\`\`

It monitors project files and mirrors updates into \`upload_server_files/\`.
`;
}

async function writeEnvTemplates() {
  await ensureDir(path.join(DEPLOY_ROOT, "frontend"));
  await ensureDir(path.join(DEPLOY_ROOT, "backend"));

  const frontExample = `# Frontend production env template
# Fill with your real production values
VITE_API_BASE_URL=https://api.example.com
VITE_APP_BASE_URL=https://app.example.com
`;
  const backExample = `# Backend production env template
# Fill with your real production values
NODE_ENV=production
PORT=8080
DATABASE_URL=postgresql://user:password@host:5432/dbname
CORS_ORIGIN=https://app.example.com
`;

  await fsp.writeFile(path.join(DEPLOY_ROOT, "frontend", ".env.production.example"), frontExample);
  await fsp.writeFile(path.join(DEPLOY_ROOT, "backend", ".env.production.example"), backExample);
}

async function writeReadme() {
  await fsp.writeFile(path.join(DEPLOY_ROOT, "README_DEPLOY.md"), deployReadmeText());
}

async function fullSync() {
  await ensureDir(DEPLOY_ROOT);
  for (const rule of COPY_RULES) {
    await syncRule(rule);
  }
  await writeEnvTemplates();
  await writeReadme();
}

async function main() {
  console.log(`[sync-deploy] Starting sync to: ${DEPLOY_ROOT}`);
  await fullSync();
  console.log("[sync-deploy] Initial sync completed.");

  if (ONCE) return;

  console.log(`[sync-deploy] Watching with ${INTERVAL_MS}ms polling...`);
  let locked = false;
  setInterval(async () => {
    if (locked) return;
    locked = true;
    try {
      await fullSync();
    } catch (e) {
      console.error("[sync-deploy] Sync error:", e && e.message ? e.message : e);
    } finally {
      locked = false;
    }
  }, INTERVAL_MS);
}

main().catch((e) => {
  console.error("[sync-deploy] Fatal:", e);
  process.exit(1);
});
