import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import providersRouter from "./providers";
import servicesRouter from "./services";
import requestsRouter from "./requests";
import reviewsRouter from "./reviews";
import packagesRouter from "./packages";
import favoritesRouter from "./favorites";
import listingsRouter from "./listings";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import settingsRouter from "./settings";
import staffRouter from "./staff";
import regionsRouter from "./regions";
import adminRouter from "./admin";
import adminPaymentsRouter from "./adminPayments";
import uploadRouter from "./upload";
import messagesRouter from "./messages";
import statsRouter from "./stats";
import supportTicketsRouter from "./supportTickets";
import propertiesRouter from "./properties";
import emailRouter from "./email";
import billingPlansRouter from "./billingPlans";
import aiChatRouter from "./ai-chat";
import chatLeadsRouter from "./chat-leads";
import chatSessionsRouter from "./chat-sessions";
import searchRouter from "./search";
import featuredAreasRouter from "./featured-areas";
import seedDemoRouter from "./seed-demo";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(uploadRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(providersRouter);
router.use(servicesRouter);
router.use(requestsRouter);
router.use(reviewsRouter);
router.use(packagesRouter);
router.use(favoritesRouter);
router.use(listingsRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(staffRouter);
router.use(regionsRouter);
router.use(adminRouter);
router.use(adminPaymentsRouter);
router.use(messagesRouter);
router.use(statsRouter);
router.use(supportTicketsRouter);
router.use(propertiesRouter);
router.use(emailRouter);
router.use(billingPlansRouter);
router.use(aiChatRouter);
router.use(chatLeadsRouter);
router.use(chatSessionsRouter);
router.use(searchRouter);
router.use(featuredAreasRouter);
router.use(seedDemoRouter);
router.use(backupRouter);

export default router;
