import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import providersRouter from "./providers";
import reviewsRouter from "./reviews";
import packagesRouter from "./packages";
import favoritesRouter from "./favorites";
import listingsRouter from "./listings";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import settingsRouter from "./settings";
import staffRouter from "./staff";
import regionsRouter from "./regions";
import adminRouter from "./admin";
import adminPaymentsRouter from "./adminPayments";
import uploadRouter from "./upload";
import messagesRouter from "./messages";
import statsRouter from "./stats";
import supportTicketsRouter from "./supportTickets";
import propertiesRouter from "./properties";
import emailRouter from "./email";
import billingPlansRouter from "./billingPlans";
import aiChatRouter from "./ai-chat";
import chatLeadsRouter from "./chat-leads";
import chatSessionsRouter from "./chat-sessions";
import searchRouter from "./search";
import featuredAreasRouter from "./featured-areas";
import propertyFeaturesRouter from "./property-features";
import seedDemoRouter from "./seed-demo";
import backupRouter from "./backup";
import updatesRouter from "./updates";
import recommendationsRouter from "./recommendations";
import adsRouter from "./ads";
import propertyReportsRouter from "./propertyReports";
import wpImportRouter from "./wpImport";
import popupsRouter from "./popups";
import marketRouter from "./market";
import userPaymentsRouter from "./userPayments";
import promotionsRouter from "./promotions";
import sseRouter from "./sse";
import menuItemsRouter from "./menuItems";

const router: IRouter = Router();

router.use(uploadRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(providersRouter);
router.use(reviewsRouter);
router.use(packagesRouter);
router.use(favoritesRouter);
router.use(listingsRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(staffRouter);
router.use(regionsRouter);
router.use(adminRouter);
router.use(adminPaymentsRouter);
router.use(messagesRouter);
router.use(statsRouter);
router.use(supportTicketsRouter);
router.use(propertiesRouter);
router.use(emailRouter);
router.use(billingPlansRouter);
router.use(aiChatRouter);
router.use(chatLeadsRouter);
router.use(chatSessionsRouter);
router.use(searchRouter);
router.use(featuredAreasRouter);
router.use(propertyFeaturesRouter);
router.use(seedDemoRouter);
router.use(backupRouter);
router.use(updatesRouter);
router.use(recommendationsRouter);
router.use(adsRouter);
router.use(propertyReportsRouter);
router.use(wpImportRouter);
router.use(popupsRouter);
router.use(marketRouter);
router.use(userPaymentsRouter);
router.use(promotionsRouter);
router.use(sseRouter);
router.use(menuItemsRouter);

export default router;
